version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/roq-web
permissions:
  - object: /var/www/roq-web
    owner: ubuntu
    group: ubuntu
  AfterInstall:
    - location: afterinstall.sh
      runas: ubuntu
  ApplicationStart:
    - location: applicationstart.sh
      runas: ubuntu
