version: 0.0
os: linux
files:
 - source: /
   destination: /var/www/roq-web/
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: stop_puma_service
      timeout: 300
      runas: root
  ApplicationStart:
   - location: start_puma_service
     timeout: 300
     runas: root
