#!/bin/bash
rvm use --default ruby-2.6.5
if [ "$APPLICATION_ENV" == "PROD" ]
then
RAILS_ENV=production bundle install
RAILS_ENV=production rake db:migrate
elif [ "$APPLICATION_ENV" == "DEV" ] 
then
RAILS_ENV=staging bundle install
RAILS_ENV=staging rake db:migrate
elif [ "$APPLICATION_ENV" == "STAGING" ]
then
RAILS_ENV=staging bundle install
RAILS_ENV=staging rake db:migrate
fi
./bin/webpack
sudo service sidekiq start
sudo service puma start

